CHANGELOG.md

Problem: outdated CHANGELOGS for v0.2.0 release (fix #454)

---

.github/workflows/android-build.yml
.github/workflows/bindings.yml
.github/workflows/ios-build.yml
Cargo.lock
README.md
common/Cargo.toml

Close #451 
1. Bump `uniffi_bindgen` to version `0.19.1`.
2. Update README.
3. Fix to always try to install `uniffi_bindgen` (with specified version) to avoid using the cache one in CI (if the version is right, will not re-install).

Problem: failed to bump crate `uniffi` to `0.19` (fix #451)

---

Makefile
example/cpp-example/CMakeLists.txt
example/cpp-example/Makefile

Problem: not compiles on apple m1 (fix #465)

---

.github/workflows/ci.yml
common/src/login.rs
common/src/transaction/cosmos_sdk.rs
common/src/transaction/ethereum.rs
common/src/transaction/nft.rs
common/src/wallet.rs

Solution: replaced the GH action with manual `cargo clippy` call
and removed the duplicate clippy steps/flow

Problem: clippy error in github action (fixes #467)

---

integration_tests/test_basic.py
integration_tests/utils.py
scripts/.env

Solution: 
- Add env: `CPP_EXAMPLE_PATH`

Problem: cpp integration test example binary path can not change (fix #475)

---

.github/workflows/ci.yml

Solution:
- Run clippy on cpp/wasm individually in ci.yml

Problem: non-default members are not tested with clippy (fix #479)

---

Cargo.lock
bindings/wasm/Cargo.toml
example/cpp-example/CMakeLists.txt
example/cpp-example/Makefile

Close:
- #485
Solution:
- Use `default-features = false` and `rustls-tls` feature for reqwest

Problem: openssl is still in used (fix #485)

---

.github/workflows/ci.yml

Solution: changed the cargo test executions to use `cargo llvm-cov`

Problem: missing test coverage (fixes #482)

---

integration_tests/test_basic.py
scripts/.env

Close:
- #495
Solution:
- Assert False, If the return string contains rust::cxxbridge1::Error

Problem: rust::cxxbridge1::Error is not detected in integration test (fix #495)

---

.github/workflows/android-build.yml
.github/workflows/bindings.yml
.github/workflows/ios-build.yml
Cargo.lock
Makefile
README.md

Close #473 
1. Use `cargo tree` command to get specified version of `uniffi` from `Cargo.lock`.
2. Add a Make command `install-uniffi-bindgen` to install this version.
3. Update CI and README.

Problem: upgrade to uniffi 0.19.2 fails (fix #473)

---

CHANGELOG.md
bindings/cpp/Cargo.toml
bindings/wasm/Cargo.toml
common/Cargo.toml

Close:
- #502
Solution:
- Update Cargo.toml (common, cpp, and wasm crates)
- Update CHANGELOG.md

Problem: Missing release v0.2.1 (fix #502)

---

CHANGELOG.md
common/src/common.udl
common/src/node/cosmos_sdk.rs

Solution:
- added basic support for denomination queries to UniFFI bindings via gRPC

Problem: missing bank denom metadata query (fixes #512)

---

LICENSE
NOTICE
docs/cpp/mdbook/book.toml
docs/cpp/sphinx/conf.py
example/js-example/package.json
integration_tests/pyproject.toml
proto-build/src/main.rs

Solution: updated the relevant notices

Problem: license notices are not up to date

---

.gitignore
Cargo.lock
bindings/cpp/src/lib.rs
common/Cargo.toml
common/src/common.udl
common/src/node/ethereum.rs
common/src/node/ethereum/erc1155.rs
common/src/node/ethereum/erc20.rs
common/src/node/ethereum/erc721.rs
common/src/node/ethereum/provider.rs
common/src/node/ethereum/utils.rs
common/src/transaction/ethereum/error.rs
example/cpp-example/main.cc

Problem: cannot set user-agent (fix #484)

---

Cargo.lock
bindings/cpp/Cargo.toml

Problem: cxx-build not updated (fix #530)

---

Cargo.lock
common/Cargo.toml
common/src/node/cosmos_sdk.rs

Close #508 
Reference the example of `DisplayFromStr`: https://crates.io/crates/serde_with

Problem: upgrade to serde_with 2 fails (fix #508)

---

bindings/cpp/Cargo.toml
bindings/cpp/LICENSE
bindings/cpp/README.md
bindings/wasm/Cargo.toml
bindings/wasm/LICENSE
bindings/wasm/README.md
common/Cargo.toml
common/LICENSE
common/README.md
proto-build/Cargo.toml
proto-build/LICENSE
proto-build/README.md
proto/LICENSE

Problem: Missing licenses (fix #570)

---

.github/workflows/android-build.yml

Problem: android integration test fails (fix #587)

---

.github/workflows/android-build.yml
.github/workflows/audit.yml
.github/workflows/bindings.yml
.github/workflows/ci.yml
.github/workflows/docs.yml
.github/workflows/ios-build.yml
.github/workflows/lint.yml
.github/workflows/linux-build.yml
.github/workflows/mac-build.yml
.github/workflows/test.yml
.github/workflows/win-build.yml

Solution: switch to dtolnay/rust-toolchain

Problem: actions-rs are not actively maintained

---

common/Cargo.toml
common/src/contract.rs
common/src/contract/erc4907-abi.json
common/src/node/ethereum.rs
common/src/node/ethereum/erc4907.rs

Solution: added a query-only feature-guarded support

Problem: ERC4907 is not supported (fixes #554)

---

bindings/cpp/src/contract.rs
example/cpp-example/cronos.cc

Problem: Incorrect testnet setting (fix #607)

---

bindings/cpp/src/lib.rs
common/src/node/ethereum/utils.rs
common/src/transaction/ethereum.rs

Problem: no building cronos tx with signature (fix #619)

---

common/src/node/ethereum/utils.rs

give valid web3url for the provider

Problem: wallet-connect construct-tx fails (fix #660)

---

common/src/transaction/ethereum.rs
proto-build/src/main.rs

Solution: fixed based on the suggestions

Problem: clippy warnings

---

Cargo.lock

Solution: `cargo update -p cpufeatures -p ecdsa -p fastrlp-deriv

Problem: yanked crates

---

Cargo.lock

Problem: dependency crate `blake2` is reported as `yanked` by cargo-audit (fix #678)

---

CHANGELOG.md
Cargo.lock
bindings/cpp/Cargo.toml
bindings/wasm/Cargo.toml
common/Cargo.toml

Close:
- #680
Solution:
- Update CHANGELOG and version number

Problem: Missing v0.3.0 release (fix #680)

---

Cargo.lock
bindings/cpp/Cargo.toml
bindings/cpp/build.rs

Solution: switch to the latest cxx-build that has
the doxygen configuration option

Problem: custom cxx-build fork

---

.github/workflows/audit.yml
Cargo.lock
bindings/cpp/Cargo.toml
bindings/wasm/Cargo.toml
bindings/wasm/src/cosmos_sdk.rs
bindings/wasm/tests/nft.rs
bindings/wasm/tests/test_helper.rs
common/Cargo.toml
common/src/transaction/cosmos_sdk/parser/base_parser.rs
common/src/transaction/cosmos_sdk/parser/structs.rs
common/src/transaction/nft.rs
proto/Cargo.toml

Solution: upgraded the related crates and small API adjustments

Problem: tendermint and ibc failed to upgrade (fixes #659, fixes #632)

---

Cargo.lock

Solution: `cargo update -p tonic-build`

Problem: yanked crate

---

CHANGELOG.md
bindings/cpp/src/ethereum.rs
common/src/transaction/ethereum.rs
contracts/contracts/GameERC721.sol
example/cpp-example/cronos.cc
example/cpp-example/main.cc

Solution: add deploying, minting example

Problem: missing cronos NFT minting (fix #458)

---

CHANGELOG.md
bindings/cpp/Cargo.toml
bindings/wasm/Cargo.toml
common/Cargo.toml

Problem: not updated for version 0.3.1 (fix #719)

---

CHANGELOG.md
common/src/node/ethereum/abi.rs
common/src/transaction/ethereum/abi_contract.rs

Problem: EthAbiToken is not cloneable (fix #727)

---

bindings/cpp/src/ethereum.rs
common/src/contract.rs
example/cpp-example/cronos.cc

Problem: missing chainid in DynamicContract send (fix #741)

---

CHANGELOG.md

Problem: changelog not updated for 0.3.2 (fix #743)

---

Cargo.lock
bindings/cpp/Cargo.toml
bindings/cpp/src/lib.rs
example/cpp-example/wallet.cc

support secure storage
add test
add save, load for any string

Problem: no secure secret storage option (fix #761)

---

bindings/cpp/Cargo.toml
bindings/cpp/src/lib.rs

Problem: cannot compile for android (fix #777)

---

example/cpp-example/CMakeLists.txt
example/cpp-example/Makefile

Problem: linux build fails (fix #788)

---

.github/CODEOWNERS

Problem: missing CODEOWNERS

---

.github/workflows/android-build.yml
.github/workflows/audit.yml
.github/workflows/bindings.yml
.github/workflows/ci.yml
.github/workflows/codeql.yml
.github/workflows/docs.yml
.github/workflows/ios-build.yml
.github/workflows/lint.yml
.github/workflows/linux-build.yml
.github/workflows/mac-build.yml
.github/workflows/test.yml
.github/workflows/win-build.yml

Solution: added the merge event

Problem: CI not executed on merge queues

---

bindings/cpp/AndroidSecureStorage/app/src/main/java/com/cronos/play/SecureStorage.kt
bindings/cpp/AndroidSecureStorage/compile.md
bindings/cpp/build.rs
bindings/cpp/compile.sh
bindings/cpp/include/android.h
bindings/cpp/src/android.cc
bindings/cpp/src/lib.rs
example/cpp-example/helper.py

Problem: missing secure storage option for android (fix #764)

---

.github/workflows/docs.yml
.github/workflows/lint.yml
.github/workflows/test.yml

Solution: pin to the nix 2.13 for the moment

Problem: nix actions fail on CI

---

CHANGELOG.md
Cargo.lock
bindings/cpp/Cargo.toml
bindings/wasm/Cargo.toml
common/Cargo.toml

Problem: missing changelog for v0.3.3 (fix #844)

---

common/src/node/ethereum/provider.rs

Problem: Request timeout is not enabled (fix #858)

---

.github/workflows/audit.yml
CHANGELOG.md
Cargo.lock
bindings/cpp/Cargo.toml
bindings/wasm/Cargo.toml
common/Cargo.toml

Problem: Missing v0.3.4 release (fix #903)

---

CHANGELOG.md
Cargo.lock
bindings/cpp/Cargo.toml
bindings/wasm/Cargo.toml
common/Cargo.toml
common/src/node/ethereum/utils.rs

Problem: ContractApproval and ContractTransfer do not implement Serialize and Deserialize (fix #908)

---

CHANGELOG.md
Cargo.lock
bindings/cpp/Cargo.toml
bindings/cpp/src/lib.rs
bindings/wasm/Cargo.toml
common/Cargo.toml
common/src/common.udl
common/src/node/ethereum/utils.rs
common/src/transaction/ethereum/error.rs

Problem: Missing wait_for_transaction_receipt (fix #914)

---

common/src/lib.rs
common/src/node.rs

Problem: cargo check fails (fix #921)

---

common/src/node/ethereum/abi.rs
common/src/transaction/ethereum/abi_contract.rs

Solution: fix array encoded as array

Problem: abi Array is encoed as FixedArray (fix #930)

---

Cargo.lock
bindings/cpp/Cargo.toml
bindings/wasm/Cargo.toml
common/Cargo.toml
common/src/lib.rs
example/cpp-example/CMakeLists.txt
example/cpp-example/Makefile

Problem: cargo clippy error (fix #932)
