- .github/workflows/linux-build.yml
- .github/workflows/win-build.yml
- Makefile
- checkmac.sh
- docs/cpp/Doxyfile
- example/cpp-example/CMakeLists.txt
- example/cpp-example/Makefile
- example/cpp-example/chainmain.cc
- example/cpp-example/cronos.cc
- example/cpp-example/helper.py
- example/cpp-example/main.cc
- example/cpp-example/sdk/CMakeLists.txt
- example/vs-example/vs-example/vs-example.vcxproj
Solution:
- Add basic cmake support and test cmake in CI
- Move the libraries and bindings to sdk
- Integrate x86_64 and amd64 in Makefile
- Add linux_build.yml
- Use rpath for mac dynamic library
- Use so file for linux dynamic library
- Simplify the process of build example by one `make`
> Problem: missing support for CMake (fix #265)

- Cargo.lock
- common/Cargo.toml
- common/src/lib.rs
- common/src/qr_code.rs
- common/src/transaction/ethereum.rs
Solution: added a basic generation parser for EIP681
(note that parsing is not fully complete,
but it should be possible to parse basic requests
> Problem: missing EIP681 support (fixes #487)

- README.md
- common/uniffi.toml
Solution:
added a basic config to the UniFFI, so that the generated bindings
expect a dynamic library similar to what setuptools expect/build
> Problem: missing Python bindings support (fixes #509)

- CHANGELOG.md
- common/src/common.udl
- common/src/node/cosmos_sdk.rs
Solution: extended the UniFFI binding to take a choice of transaction
broadcast modes
> Problem: missing a choice of transaction broadcast modes (fixes #513)

- Cargo.lock
- bindings/cpp/Cargo.toml
- bindings/wasm/Cargo.toml
- common/Cargo.toml
- common/src/transaction/cosmos_sdk.rs
- common/src/transaction/cosmos_sdk/parser/base_parser.rs
- common/src/transaction/cosmos_sdk/parser/crypto_org_parser.rs
- proto/Cargo.toml
- proto/src/lib.rs
Solution:
- switched ethers from git version to 0.15 + added abi-gen feature
- updated the conflicting dependencies (cosmrs, ibc-rs...)
- adjusted API based on the breaking changes in cosmrs (MsgProto->TypeUrl)
> Problem: ethers not updated (fixes #407)

- mobile_modules/android_module/dwclib/src/androidTest/java/com/crypto/dwclib/ExampleInstrumentedTest.kt
Disable getAccountBalanceWorkTest test case in android, to avoid CI failures due to network issues.
> Problem: Android ci failed with network (fix #578)

- Cargo.lock
Solution: update all uniffi crates to the same version
> Problem: upgrading uniffi_macros to v0.19.5 fails (fixes #573)

- Cargo.lock
Solution: updated axum-core to a patched version
> Problem: vulnerable crate warning

- Cargo.lock
- bindings/wasm/Cargo.toml
- bindings/wasm/src/cosmos_sdk.rs
- bindings/wasm/src/ethereum.rs
Solution: switched to `serde-wasm-bindgen` and upgraded the wasm-bindgen-related crates
> Problem: clippy fails for wasm-bindgen-related crate upgrades (fixes #597)

- common/src/node/ethereum/abi.rs
Close #600 
Fixed to parse missing type `function` to `EthAbiParamType::FixedBytes(24)`.
> Problem: lose ABI parameter type `function` when parsing `EthAbiParamType` from a string (fix #600)

- Cargo.lock
- common/Cargo.toml
- common/src/node/ethereum/abi.rs
- common/src/node/ethereum/eip712.rs
- common/src/node/ethereum/eip712/deserializer.rs
- common/src/qr_code.rs
Solution: replaced the custom parser with a peg-based generated parser; removed the aliases unsupported by EIP712 and pure ABI types; created a wrapper type for EIP712 to capture the allowed ABI values
> Problem: ABI parameter type parsing does not parse tuples (fixes #339)

- common/src/common.udl
- common/src/contract.rs
- common/src/transaction/ethereum/abi_contract.rs
- common/src/transaction/ethereum/error.rs
Solution: added a basic contract call creation using the raw ABI strings
> Problem: missing support for general contract calls (fixes #517)

- Cargo.lock
- common/Cargo.toml
Solution: bump uniffi crates together
> Problem: upgrading to uniffi 0.21 fails (fixes #633)

- Cargo.lock
- bindings/cpp/Cargo.toml
- bindings/cpp/src/lib.rs
- common/Cargo.toml
- common/src/login.rs
Solution: adjusted the API usage (verify is now async, because it could take the HTTP provider for additional verification against onchain state)
> Problem: upgrade to siwe 0.5 fails (fixes #644)

- common/src/node/ethereum/provider.rs
Close:
- #676
Solution:
- Only get `G_AGENTINFO` in get_ethers_provider
> Problem: error is generated if set_ethers_httpagent called after get_ethers_provider fix (#676)

- CHANGELOG.md
- Cargo.lock
- bindings/cpp/src/lib.rs
- bindings/wasm/Cargo.toml
- bindings/wasm/src/cosmos_sdk.rs
- bindings/wasm/tests/test_helper.rs
- common/Cargo.toml
- common/src/common.udl
- common/src/node/cosmos_sdk.rs
- common/src/node/cosmos_sdk/balance_query.rs
- example/android_example/app/src/main/java/com/example/android_example/MainActivity.kt
- example/cpp-example/chainmain.cc
- example/ios-example/ios-example/ContentView.swift
- example/js-example/index.js
- mobile_modules/android_module/dwclib/src/androidTest/java/com/crypto/dwclib/ExampleInstrumentedTest.kt
- scripts/.env
Part of issue https://github.com/crypto-com/defi-wallet-core-rs/issues/511 (will fix `get_account_details` in another PR)
Replace REST API with `grpc-web` for `get_account_balance` functions.
> Problem: unnecessary use of REST API instead of grpc-web (`get_account_balance` part)

- Cargo.lock
- bindings/cpp/Cargo.toml
- bindings/cpp/src/uint.rs
- bindings/wasm/Cargo.toml
- common/Cargo.toml
- common/src/common.udl
- common/src/node/ethereum/utils.rs
- common/src/transaction/ethereum.rs
- common/src/wallet.rs
Solution: upgraded ethers to 1.0
+ had to disable bip39 default features due to transitive dependency conflicts
and adjust API, as std/error isn't provided
from no_std bip39
> Problem: pre-stable ethers

- Cargo.lock
- common/Cargo.toml
Solution: bump the related uniffi crates together
> Problem: upgrade to uniffi 0.22 fails (fixes #758)

- Cargo.lock
- bindings/cpp/Cargo.toml
- bindings/wasm/Cargo.toml
- common/Cargo.toml
- common/src/node/cosmos_sdk.rs
- common/src/transaction/cosmos_sdk.rs
- common/src/transaction/cosmos_sdk/parser/structs/cosmos_raw_msg.rs
- proto/Cargo.toml
Solution: bumped all related crates (ibc, cosmrs, proto ones...) together
> Problem: upgrade to tendermint 0.28 fails (fixes #705)

- Cargo.lock
- common/Cargo.toml
- common/src/transaction/cosmos_sdk.rs
- common/src/transaction/cosmos_sdk/parser/structs/cosmos_raw_msg.rs
Solution: added a feature flag and adapted the msgtransfer fields based on the breaking changes
> Problem: upgrading to ibc 0.27 fails (fixes #787)

- Cargo.lock
- common/Cargo.toml
- common/src/transaction/cosmos_sdk/parser/structs.rs
Solution: changed from the deprecated method to the current base64 API
> Problem: upgrading base64 to 0.21 fails (fixes #775)

- Cargo.lock
- common/Cargo.toml
Solution: bump ibc and ibc-proto together to their respective versions
> Problem: upgrade to ibc 0.28 fails (fixes #828)

- Cargo.lock
- bindings/cpp/Cargo.toml
- bindings/cpp/src/lib.rs
Solution: updated the entry API to return an error if failed, as done in 2.0
> Problem: upgrade to keyring 2.0 fails (fixes #837)

- Cargo.lock
- bindings/cpp/Cargo.toml
- bindings/wasm/Cargo.toml
- common/Cargo.toml
- common/src/common.udl
- common/src/transaction/ethereum.rs
- common/src/transaction/ethereum/error.rs
Solution: add one extra chain id parser error type
> Problem: upgrade to ethers 2.0 fails (fixes #856)

- Cargo.lock
This reverts commit 455caef92170c24ad6838a9364ae21113e01ca8a.
> Revert "Bump serde from 1.0.152 to 1.0.158 (#880)"
